services: 
  frontend:
    build: home-ca-frontend
    environment:
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - SSL_CERT=${SSL_CERT}
      - SSL_KEY=${SSL_KEY}
    ports:
      - 443:443