using home_ca_backend.Core.CertificateAuthorityServerAggregate;

namespace home_ca_backend.Application.AddIntermediateCertificateAuthority;

public record ValidResponse(CertificateAuthorityId CreatedCertificateAuthorityId) : AddIntermediateCertificateAuthorityResponse(true);